package domain

/** Represents a declaration of intent for an [[Agent]] during a simulation step. Actions are generated by a
  * [[Behavior]] and describe what the agent intends to do (e.g., moving or communicating), leaving their resolution to
  * the simulation engine.
  *
  * @tparam S
  *   The generic type representing the internal state of the Agent.
  */
enum Action[S]:

  /** Expresses the intent to move within the environment.
    *
    * @param velocity
    *   A [[V2d]] vector representing the desired movement direction and magnitude.
    */
  case Move(velocity: V2d) extends Action[S]

  /** Expresses the intent to store information inside the agent's internal memory.
    *
    * @param event
    *   The [[MemoryEvent]] to be recorded.
    */
  case Remember(event: MemoryEvent) extends Action[S]

  /** Expresses the intent to share knowledge directly with another specific agent.
    *
    * @param target
    *   The unique identifier ([[AgentId]]) of the recipient agent.
    * @param event
    *   The [[MemoryEvent]] containing the information to share.
    */
  case Tell(target: AgentId, event: MemoryEvent) extends Action[S]

  /** Expresses the intent to bring a completely new agent into the simulation.
    *
    * @param state
    *   The initial state (of type [[S]]) for the newly spawned agent.
    */
  case Spawn(state: S) extends Action[S]

  /** Expresses the intent to terminate the agent's lifecycle, removing it from the simulation.
    */
  case Die() extends Action[S]
